# inference setting
last_embed_region: -150
batch_size: 4
num_workers: 2
seed: 256

# model setting
fine_tune_layers: 0 # Options: 0, -1, ..., -layer_num. e.g. -1 means finetune the last layer
embed_dim: 480 # Options: 480 (ESM-2 35M or SaProt 35M), 1280 (ESM-2 650M or SaProt 650M)
pooling: "mean"

# data setting
save_dir: "./virtual_screening/saprot_t12_vs"
saprot_file: "./data/params/SaProt_35M_AF2.pt"
saprot_ensemble_path: "./virtual_screening/saprot_35M_ensemble_saprot-12layers-[ft-11]"
mutation_file_path: "data/processed/5nnk/5nnk_nngg_mut_num.csv"
seq_file_path: "data/protein/5nnk"
vs_token_path: "./virtual_screening/saprot_tokens"
